# Generated by Django 3.0.8 on 2020-09-06 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200906_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='watclist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
