# Generated by Django 3.0.8 on 2020-09-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200906_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listings',
            old_name='watclist',
            new_name='watchlist',
        ),
    ]
