# Generated by Django 3.0.8 on 2020-09-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200907_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
